### ISSUE TITLE
Issue when using `Nullable` SQL type

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-sink-sql#11]
Having issues using `Nullable` field type
https://clickhouse.com/docs/en/sql-reference/data-types/nullable

```sql
CREATE TABLE IF NOT EXISTS blocks
(
    `id` String,
    `difficulty` Int64
)
ENGINE = ReplacingMergeTree
PRIMARY KEY id
ORDER BY id
```

Substreams test code logic

```rust
match header.difficulty {
    Some(difficulty) => row.change("difficulty", ("", "123")),
    None => row,
};
```

## ❌ Errors

- when difficulty=123
> 2024-07-26T23:47:02.098+0200 ERRO (sink-sql) handle BlockScopedData message at block #10 (4ff4a38b278ab49f7739d3a4ed4e12714386a9fdf72192f2e8f7da7822f10b4d): failed to flush at block #10 (4ff4a38b278ab49f7739d3a4ed4e12714386a9fdf72192f2e8f7da7822f10b4d): dialect flush: failed to get values: converting value "123" to type "*int64" in column "difficulty": unsupported pointer type *int64

- when difficulty=null (empty)
> 2024-07-26T23:47:51.667+0200 ERRO (sink-sql) handle BlockScopedData message at block #10 (4ff4a38b278ab49f7739d3a4ed4e12714386a9fdf72192f2e8f7da7822f10b4d): failed to flush at block #10 (4ff4a38b278ab49f7739d3a4ed4e12714386a9fdf72192f2e8f7da7822f10b4d): dialect flush: executing for entry ["0x476574682f76312e302e302f6c696e75782f676f312e342e32" '\x00' 'ᎈ' '\x00' "0x88e96d4537bea4d9c05d12549907b32561d3bf31f45aae734cdc119f13406cb6" "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" "0x05a56e2d52c817161883f50c441c3228cfe54d9f" "0x969b900de27b6ac6a67742365dd65f55a0526c41fd18e1b16f1a1215c2e66f59" '�' '\x01' "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347" "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3" "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421" "537" "0xd67e4d450343046425ae4271474353857ab860dbc0a1dde64b41b5cd3a532bf3" '\x00' '�' '\x00' "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"]: clickhouse [Append]:  clickhouse: expected 20 arguments, got 19

## ✅ work around solution

Set null values as `0`

**Comment by DenisCarriere** [comment]
Same issue with `Nullable(String)`

```sql
CREATE TABLE IF NOT EXISTS logs
(
    topic0              String,
    topic1              Nullable(String),
    topic2              Nullable(String),
    topic3              Nullable(String),
```

## ❌ Error `unsupported pointer type *string`

> 2024-07-28T11:28:39.418+0200 ERRO (sink-sql) handle BlockScopedData message at block #1598910 (f83b4bd9b91d157f2f6d8c3ad90dd69c1b7c050f3a372dc0af792a2533c6b5fe): failed to flush at block #1598910 (f83b4bd9b91d157f2f6d8c3ad90dd69c1b7c050f3a372dc0af792a2533c6b5fe): dialect flush: failed to get values: converting value "0x00000000000000000000000012dbd4c669e3e860a6432dcb69c8ded6b77be616" to type "*string" in column "topic1": unsupported pointer type *string

## ❌  Error `invalid memory address or nil pointer dereference`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x1058b7224]

goroutine 94 [running]:
github.com/streamingfast/substreams-sink-sql/db.convertOpToClickhouseValues(0x14001034f90)
        /Users/denis/Github/substreams-sink-sql/db/dialect_clickhouse.go:174 +0x1d4
github.com/streamingfast/substreams-sink-sql/db.clickhouseDialect.Flush({}, {0x1?, 0x0?}, {0x1066e34b0, 0x140001eab10}, 0x140000e4780, {0x1066e34b0?, 0x1065c4820?}, 0x1400088e540?)
        /Users/denis/Github/substreams-sink-sql/db/dialect_clickhouse.go:64 +0x78c
github.com/streamingfast/substreams-sink-sql/db.(*Loader).Flush(0x140000e4780, {0x105a3bda2?, 0x18584e?}, {0x14000512030, 0x28}, 0x1400009a8d8, 0x18584e)
        /Users/denis/Github/substreams-sink-sql/db/flush.go:29 +0x1a0
github.com/streamingfast/substreams-sink-sql/sinker.(*SQLSinker).HandleBlockScopedData(0x14000825c00, {0x1066e34e8, 0x14000516050}, 0x14000715180, 0x10789046a, 0x1400009a8d8)
        /Users/denis/Github/substreams-sink-sql/sinker/sinker.go:125 +0x5d0
github.com/streamingfast/substreams-sink.(*Sinker).doRequest(0x140002bc160, {0x1066e34e8, 0x14000516050}, 0x14000d3a038, 0x14000b34b80, {0x1066c1860, 0x14000883840}, {0x14000883830, 0x1, 0x1}, ...)
        /Users/denis/go/pkg/mod/github.com/streamingfast/substreams-sink@v0.3.4/sinker.go:485 +0x14ec
github.com/streamingfast/substreams-sink.(*Sinker).run(0x140002bc160, {0x1066e34e8, 0x14000516050}, 0x14000d3a038, {0x1066d9ce8, 0x14000825c00})
        /Users/denis/go/pkg/mod/github.com/streamingfast/substreams-sink@v0.3.4/sinker.go:280 +0x624
github.com/streamingfast/substreams-sink.(*Sinker).Run(0x140002bc160, {0x1066e34e8, 0x14000516050}, 0x14000d3a038, {0x1066d9ce8, 0x14000825c00})
        /Users/denis/go/pkg/mod/github.com/streamingfast/substreams-sink@v0.3.4/sinker.go:199 +0x38c
github.com/streamingfast/substreams-sink-sql/sinker.(*SQLSinker).Run(0x14000825c00, {0x1066e34e8, 0x14000516050})
        /Users/denis/Github/substreams-sink-sql/sinker/sinker.go:89 +0x658
created by github.com/streamingfast/cli.(*Application).SuperviseAndStart in goroutine 1
        /Users/denis/go/pkg/mod/github.com/streamingfast/cli@v0.0.4-0.20230825151644-8cc84512cd80/application.go:102 +0x370
make: *** [sql-run] Error 2
```

**Comment by DenisCarriere** [comment]
Clickhouse best practices recommend avoiding using `Nullable` fields
https://clickhouse.com/docs/en/cloud/bestpractices/avoid-nullable-columns

This issue isn't fixed in the substreams sink sql, however `Nullable` types shouldn't be used

Alternative setting integer values to `0` and String values to `""` empty string
